import React from "react";
import Image from "next/image";
import Link from "next/link";
import Commonbtn from "@/components/Commonbtn";
export const metadata = {
  title: "About",
  description: "Generated by create next app",
};
const Page = () => {
  const data = [
    {
      img: "/images/behind-1.png",
      para1: "Naman",
      para2: "Radial code",
    },
    {
      img: "/images/behind-1.png",
      para1: "Naman",
      para2: "Radial code",
    },
    {
      img: "/images/behind-1.png",
      para1: "Naman",
      para2: "Radial code",
    },
  ];
  return (
    <div className="container max-w-[1140px] mx-auto">
      <div className="flex flex-col  min-h-screen justify-center items-center">
        <Link
          href="/ "
          className=" text-base md:text-[30px]  rounded-[30px] bg-transparent border-[4px] border-solid border-black p-3 md:p-5 mb-5 uppercase font-bold"
        >
          Go to home -
        </Link>
        <div className="flex flex-col md:flex-row gap-4 ">
          {data.map((obj, i) => (
            <div key={i} className="bg-black rounded-lg p-4">
              <Image src={obj.img} width={400} height={400} alt="hello" />
              <div className="fs-xl flex flex-col items-center ">
                <p className="text-white text-xxl mt-3 fw-bold">{obj.para1}</p>
                <p className="text-white text-xxl fw-bold">{obj.para2}</p>
              </div>
            </div>
          ))}
        </div>
        <Commonbtn text="Show" />
      </div>
    </div>
  );
};

export default Page;
